[project]
name = "osubot"
version = "0.1.0"
description = "An all in one osu! bot for discord"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "aiosqlite>=0.21.0",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "ossapi>=5.3.2",
    "rosu-pp-py>=3.1.0",
]
