[project]
name = "osubot"
version = "0.1.0"
description = "An all in one osu! bot for discord"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "dotenv>=0.9.9",
]
